services:
  - type: web
    name: chatapp
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k eventlet -w 1 main:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: chatapp-db
          property: connectionString
    plan: free

databases:
  - name: chatapp-db
    plan: free 