services:
  - type: web
    name: chatapp
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
    plan: free

databases:
  - name: chatapp-db
    plan: free 